---
title: "Data Import"
output: github_document
---

This file is for doing data import.

```{r}
library(tidyverse)
library(readxl)
```

Import our first dataset

```{r}
litters_df = 
  read_csv(file = "data/FAS_litters.csv",
           na = c("", "NA", ".") ## by default, na includes missing and NA values, but this particular dataset has "." as a missing value.
           )

litters_df = janitor::clean_names(litters_df)
```

Import our second dataset.

```{r}
pups_df = 
  read_csv(file = "data/FAS_pups.csv", 
           skip = 3, ##skip=3 to skip first 3 rows in csv file w no data
           na = c("", "NA", ".")
           ) 

pups_df = janitor::clean_names(pups_df)
```

## Look at the data

```{r}
litters_df
pups_df
```

Head or tail

```{r}
head(litters_df, 20)  ## to look at first 20 rows

tail(pups_df, 5)  ## to look at last 5 rows
```

Skimming

```{r}
skimr::skim(pups_df)
```

## Excel import

use library 'readxl' here

```{r}
mlb_df = read_excel("data/mlb11.xlsx")
```

Look at the data

```{r}
mlb_df
```

Load LotR data

Import FOTR words

```{r}
fotr_df =
  read_excel("data/LotR_Words.xlsx",
             range = "B3:D6")

fotr_df
```

Import Two Towers
```{r}
tt_df =
  read_excel("data/LotR_Words.xlsx",
             range = "F3:H6")

tt_df
```








